/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int START_PROGRAM = 9;
  /** RegularExpression Id. */
  int END_PROGRAM = 10;
  /** RegularExpression Id. */
  int TIPO = 11;
  /** RegularExpression Id. */
  int LETRA = 12;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "<NUM>",
    "\"START\"",
    "\"END\"",
    "<TIPO>",
    "<LETRA>",
    "<IDENTIFICADOR>",
    "\";\"",
    "\"{\"",
    "\"}\"",
  };

}
